module.exports = {
    add: require('./command_add'),
    archive: require('./command_archive'),
    checkout: require('./command_checkout'),
    clean: require('./command_clean'),
    clone: require('./command_clone'),
    commit: require('./command_commit'),
    describe: require('./command_describe'),
    fetch: require('./command_fetch'),
    log: require('./command_log'),
    merge: require('./command_merge'),
    pull: require('./command_pull'),
    push: require('./command_push'),
    rebase: require('./command_rebase'),
    remote: require('./command_remote'),
    reset: require('./command_reset'),
    revParse: require('./command_revParse'),
    rm: require('./command_rm'),
    stash: require('./command_stash'),
    tag: require('./command_tag'),
    diff: require('./command_diff'),
    apply: require('./command_apply'),
    status: require('./command_status')
};
